name: first-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu:latest
    steps:
      - name: Print hello
        run: echo "Hello world!"
      - name: Print goodbye
        run: echo "Done bye!"
